source 'https://rubygems.org'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport', '~>4.1'
gem 'activerecord', '~>4.1'
gem 'bcrypt-ruby'

gem 'rake'

gem 'shotgun'
gem 'thin'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'rspec'
  gem 'capybara'
  gem 'jasmine'
  gem 'database_cleaner'
end

group :test, :development do
  gem 'factory_girl'
  gem 'faker'
end
